export const GET_BABIES_SUCCESS = 'GET_BABIES_SUCCESS';
export const GET_BABIES_FAILED = 'GET_BABIES_FAILED';
export const FETCH_BABIES = 'FETCH_BABIES';
export const NEW_BABY_SUCCESS = 'NEW_BABY_SUCCESS';
export const NEW_BABY_FAILED = 'NEW_BABY_FAILED';
export const SELECT_BABY = 'SELECT_BABY';
export const UPDATE_BABY_LASTFOOD = 'UPDATE_BABY_LASTFOOD';
export const UPDATE_BABY_LASTPOOP = 'UPDATE_BABY_LASTPOOP';
