export const GET_EXTRACTIONS_SUCCESS = 'GET_EXTRACTIONS_SUCCESS';
export const GET_EXTRACTIONS_FAILED = 'GET_EXTRACTIONS_FAILED';
export const FETCH_EXTRACTIONS = 'FETCH_EXTRACTIONS';
export const NEW_EXTRACTION_SUCCESS = 'NEW_EXTRACTION_SUCCESS';
export const NEW_EXTRACTION_FAILED = 'NEW_EXTRACTION_FAILED';