export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_FAILED = 'GET_FOODS_FAILED';
export const FETCH_FOODS = 'FETCH_FOODS';
export const NEW_FOOD_SUCCESS = 'NEW_FOOD_SUCCESS';
export const NEW_FOOD_FAILED = 'NEW_FOOD_FAILED';