export const GET_POOPS_SUCCESS = 'GET_POOPS_SUCCESS';
export const GET_POOPS_FAILED = 'GET_POOPS_FAILED';
export const FETCH_POOPS = 'FETCH_POOPS';
export const NEW_POOP_SUCCESS = 'NEW_POOP_SUCCESS';
export const NEW_POOP_FAILED = 'NEW_POOP_FAILED';